name: EndlessEnchants
author: EndlessTeamWork
main: it.endless.endlessEnchants.Main
version: 1.0
softdepend: [Vault, Factions, WorldEdit]
description: >
             A Plugin full of Custom Enchantments.
commands:
  endlessEnchants:
    description: Opens the Enchanter GUI.
    aliases: [ee, enchanter]
  tinkerer:
    description: Opens the Tinker GUI.
    aliases: tinker
  blacksmith:
    description: Opens the Black Smith GUI.
    aliases: [bsmith, blacks, bs]
  gkit:
    description: Opens the GKitz GUI.
    aliases: [gkitz, gkits]